### ISSUE TITLE
an error in codes

### ISSUE THREAD

**Issue by kkasra12** [freesinger/density_peak_clustering#7]
take a look at this:
https://github.com/freesinger/density_peak_clustering/blob/fe0898ef5b4555cfe37aeccdc0ea0d6d160dadbd/cluster.py#L54

you cannot raise a string in python for example:
```python
>>> raise "test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```
The correct form is:
```python
raise KeyError('Key error: key does not exist!')
```
if you run this line in interpreter you will face:
```python
>>> raise KeyError('Key error: key does not exist!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'Key error: key does not exist!'
```

**Comment by freesinger** [comment]
Thanks, would you mind making a pull request?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kasra ***@***.***>
Sent: Thursday, July 22, 2021 4:27:11 PM
To: freesinger/density_peak_clustering ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [freesinger/density_peak_clustering] an error in codes (#7)


take a look at this:
https://github.com/freesinger/density_peak_clustering/blob/fe0898ef5b4555cfe37aeccdc0ea0d6d160dadbd/cluster.py#L54

you cannot raise a string in python for example:

>>> raise "test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException

The correct form is:

raise KeyError('Key error: key does not exist!')

if you run this line in interpreter you will face:

>>> raise KeyError('Key error: key does not exist!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'Key error: key does not exist!'
